# Create a Persistent Volume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi  # Size of the PV
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/mysql # Local path on the host machine
